name: Build Fedora ISO

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build the ISO in a Fedora container
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c "
          sudo dnf install -y livecd-tools
          sudo livemedia-creator --ks=your-kickstart-file.ks --no-virt --resultdir=/workspace/output --image-name='GbrlSouza-Fedora.iso'
        "

    - name: Upload to TeraBox
      run: rclone copy ./output/GbrlSouza-Fedora.iso terabox:/my-folder/