name: Build Ubuntu ISO

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y genisoimage python3-pip curl
        pip install pykickstart
        curl https://rclone.org/install.sh | sudo bash

    - name: Install Ubuntu Customization Kit
      run: |
        sudo add-apt-repository ppa:uck-team/ppa
        sudo apt-get update
        sudo apt-get install -y uck

    - name: Build Ubuntu ISO
      run: |
        mkdir -p ~/ubuntu-iso
        cp -r /workspace/* ~/ubuntu-iso
        uck-remaster --target ~/ubuntu-iso --name "GbrlSouza-Ubuntu"

    - name: Upload to TeraBox
      run: rclone copy ./output/GbrlSouza-Ubuntu.iso terabox:/my-folder/