name: Create ISO

on:
  push:
    branches:
      - main

jobs:
  create-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mkisofs
        run: sudo apt-get install genisoimage

      - name: Create ISO
        run: |
          mkdir -p /tmp/iso
          cp -r ./path-to-files/* /tmp/iso
          genisoimage -o /tmp/iso_output.iso -J -R /tmp/iso
      
      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-iso-file
          path: /tmp/iso_output.iso